[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
stablecoin = "BsjcJ9E8CS5BMvP2VLErNUMiFSLVP9u2hifKLdYJtJE7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest tests/*.ts tests/*.js"
