[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
crud = "DyRyZ1gGV4SgDpQFumqVHmNS8dc5ZdzS7FzHLXLVk6fv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"
