import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        <h1 className={styles.title}>
          Welcome to <a href="">RainbowKit</a> + <a href="">wagmi</a> +{" "}
          <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a className={styles.card} href="https://rainbowkit.com">
            <h2>RainbowKit Documentation &rarr;</h2>
            <p>Learn how to customize your wallet connection flow.</p>
          </a>

          <a className={styles.card} href="https://wagmi.sh">
            <h2>wagmi Documentation &rarr;</h2>
            <p>Learn how to interact with Ethereum.</p>
          </a>

          <a
            className={styles.card}
            href="https://github.com/rainbow-me/rainbowkit/tree/main/examples"
          >
            <h2>RainbowKit Examples &rarr;</h2>
            <p>Discover boilerplate example RainbowKit projects.</p>
          </a>

          <a className={styles.card} href="https://nextjs.org/docs">
            <h2>Next.js Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a
            className={styles.card}
            href="https://github.com/vercel/next.js/tree/canary/examples"
          >
            <h2>Next.js Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            className={styles.card}
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <div className="flex h-[360px] bg-emerald-700 flex-wrap justify-center items-center rounded-3xl">
        {Array.from(Array(5).keys()).map((i) => {
          let t_html = `${i}`.padStart(2, "0").repeat(10)+`<p style="font-size: 30px">&#${127872+i};</p>`;
          return <div key={i} className=" m-4 p-6 w-1/5 hover:outline-4 hover:outline-offset-8 hover:outline-green-900 hover:border-red-800 hover:outline-dashed hover:border-4 hover:ring-4 hover:ring-yellow-500 bg-slate-600 border-red-800 text-red-500 text-center rounded-2xl" dangerouslySetInnerHTML={{__html: t_html}}/>;
        })}
      </div>

      <div className="grid grid-flow-row grid-cols-4 h-[1000px] bg-emerald-700 rounded-3xl">
        {Array.from(Array(11).keys()).map((i) => {
          let t_html = `${i}`.padStart(2, "0").repeat(10)+`<p style="font-size: 100px">&#${127872+i};</p>`;
          return <div key={i} className=" m-4 p-6 hover:scale-[108%] hover:delay-0 transition ease-in-out delay-1000 duration-1000 bg-slate-600 border-red-800 text-red-500 text-center rounded-2xl" dangerouslySetInnerHTML={{__html: t_html}}/>;
        })}
      </div>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
